language: go
go:
  - 1.9
  - "1.10"
  - tip
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - portaudio19-dev
      - libportmidi-dev
matrix:
  allow_failures:
    - go: tip

go_import_path: buddin.us/shaden

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portmidi portaudio; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CGO_LDFLAGS="-lportmidi -lporttime -L/usr/lib -L/usr/local/lib"; fi
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -race -service=travis-ci
